[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
runner = [
    "sh", "-c",
    '''
    if [ "$(uname -m)" = "aarch64" ]; then
        exec "$@"
    else
        exec qemu-aarch64 -L /usr/aarch64-linux-gnu/ "$@"
    fi
    ''',
    "sh"
]
