name: build aarch64

permissions:
  contents: read # This is required to allow the workflow to read the repository contents

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality-checks:
    name: Code Quality Checks (non-voting)
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run code formatter
        run: cargo fmt -- --check
      - name: Run Linter
        run: cargo clippy -- -D warnings
      
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Build the project
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --verbose
      - name: Cache cargo registry, index, and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "coverage"
          cache-targets: false
      - name: Install code coverage dependencies
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov --locked
      - name: Generate coverage
        run: cargo llvm-cov --lcov --lib --output-path lcov.info
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: lcov.info
      - name: list folder content
        run: |
          ls -la
          ls -la target/
          ls -la target/debug
      - name: Run executable
        run: ./target/debug/tiny-wasm tests/assets/empty-fn.wat
