name: build aarch64

permissions:
  contents: read # This is required to allow the workflow to read the repository contents

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  code-quality-checks:
    name: Code Quality Checks
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run code formatter
        run: |
          cargo fmt -- --check 2>&1 | while IFS= read -r line; do
            echo "::warning::$line"
          done
        continue-on-error: true
      - name: Run Linter
        run: |
          cargo clippy --message-format=json | \
          jq -r 'select(.reason=="compiler-message") | .message.rendered' | \
          while read -r line; do
            echo "::warning::$line"
          done
        continue-on-error: true
      
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04-arm
    needs: code-quality-checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Build the project
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --lib --tests
      # - name: Cache cargo registry, index, and build artifacts
      #   uses: Swatinem/rust-cache@v2
      #   with:
      #     cache-targets: false
      #     cache-all-crates: true
      - name: Install code coverage dependencies
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov --locked
      - name: Generate coverage
        run: cargo llvm-cov --lcov --ignore-filename-regex '(webassembly|base128)' --output-path lcov.info
      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          files: lcov.info
      - name: Run executable
        run: ./target/debug/tiny-wasm -m tests/assets/empty-fn.wasm
