name: build aarch64

permissions:
  contents: read # This is required to allow the workflow to read the repository contents

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Build the project
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --verbose
      - name: Install dependencies
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov
      - name: Generate coverage
        run: cargo llvm-cov --lcov --output-path lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Run executable
        run: ./target/debug/rust-tiny-wasm
